application: startechconf
version: 4
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /favicon.png
  static_files: media/favicon.png
  upload: media/favicon.png

- url: /presentation.pdf
  static_files: media/docs/startechconf-presentation.pdf
  upload: media/docs/startechconf-presentation.pdf

- url: /presentacion.pdf
  static_files: media/docs/startechconf-presentacion.pdf
  upload: media/docs/startechconf-presentacion.pdf

- url: /media
  static_dir: media
  
- url: .*
  script: main.py
