application: startechconf-site
version: 4
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^media/docs/terminos-condiciones-participa.pages
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^Gruntfile\.js
- ^node_modules/(.*/)?
- ^.sass-cache/(.*/)?
- datastore.sqlite

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /favicon.png
  static_files: media/favicon.png
  upload: media/favicon.png

- url: /icon_57x57.png
  static_files: media/icon_57x57.png
  upload: media/icon_57x57.png

- url: /icon_72x72_hdpi.png
  static_files: media/icon_72x72_hdpi.png
  upload: media/icon_72x72_hdpi.png

- url: /icon_114x114.png
  static_files: media/icon_114x114.png
  upload: media/icon_114x114.png

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /sitemap.xml
  static_files: media/sitemap.xml
  upload: media/sitemap.xml

- url: /presentation.pdf
  static_files: media/docs/startechconf-presentation.pdf
  upload: media/docs/startechconf-presentation.pdf

- url: /presentacion.pdf
  static_files: media/docs/startechconf-presentacion.pdf
  upload: media/docs/startechconf-presentacion.pdf

- url: /terminos-condiciones-participa.pdf
  static_files: media/docs/terminos-condiciones-participa.pdf
  upload: media/docs/terminos-condiciones-participa.pdf

- url: /fb
  static_dir: fb

- url: /media
  static_dir: media

- url: /2013/media
  static_dir: 2013/media

- url: /oauth/
  script: main.py

- url: /salir/
  script: main.py

- url: /participa
  script: main.py

- url: .*
  script: main.py
